<?php

namespace Tests\Unit\Policies;

use App\Models\Person;
use App\Models\User;
use App\Policies\PersonPolicy;
use PHPUnit\Framework\TestCase;

class PersonPolicyTest extends TestCase
{
    private Person $person;
    private PersonPolicy $policy;
    private User $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->person = new Person();
        $this->user = new User();
        $this->policy = new PersonPolicy();
    }

    public function test_view_any(): void
    {
        $this->assertTrue($this->policy->viewAny($this->user));
    }

    public function test_view(): void
    {
        $this->assertTrue($this->policy->view($this->user, $this->person));
    }

    public function test_create(): void
    {
        $this->assertTrue($this->policy->create($this->user));
    }

    public function test_update(): void
    {
        $this->assertTrue($this->policy->update($this->user, $this->person));
    }

    public function test_delete(): void
    {
        $this->assertTrue($this->policy->delete($this->user, $this->person));
    }

    public function test_restore(): void
    {
        $this->assertTrue($this->policy->restore($this->user, $this->person));
    }

    public function test_force_delete(): void
    {
        $this->assertTrue($this->policy->forceDelete($this->user, $this->person));
    }
}
