<?php

namespace Tests\Unit\Policies;

use App\Models\Position;
use App\Policies\PositionPolicy;
use Tests\TestCase;

class PositionPolicyTest extends TestCase
{
    private Position $position;

    private PositionPolicy $policy;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->position = new Position;
        $this->policy = new PositionPolicy;
    }

    public function test_view_any(): void
    {
        $this->assertTrue($this->policy->viewAny($this->user));
    }

    public function test_view(): void
    {
        $this->assertTrue($this->policy->view($this->user, $this->position));
    }

    public function test_create(): void
    {
        $this->assertTrue($this->policy->create($this->user));
    }

    public function test_update(): void
    {
        $this->assertTrue($this->policy->update($this->user, $this->position));
    }

    public function test_delete(): void
    {
        $this->assertTrue($this->policy->delete($this->user, $this->position));
    }

    public function test_restore(): void
    {
        $this->assertTrue($this->policy->restore($this->user, $this->position));
    }

    public function test_force_delete(): void
    {
        $this->assertTrue($this->policy->forceDelete($this->user, $this->position));
    }
}
