<?php

namespace Tests\Unit\Policies;

use App\Models\Sport;
use App\Models\User;
use App\Policies\SportPolicy;
use Tests\TestCase;

class SportPolicyTest extends TestCase
{
    private Sport $sport;

    private SportPolicy $policy;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sport = new Sport;
        $this->user = new User;
        $this->policy = new SportPolicy;
    }

    public function test_view_any(): void
    {
        $this->assertTrue($this->policy->viewAny($this->user));
    }

    public function test_view(): void
    {
        $this->assertTrue($this->policy->view($this->user, $this->sport));
    }

    public function test_create(): void
    {
        $this->assertTrue($this->policy->create($this->user));
    }

    public function test_update(): void
    {
        $this->assertTrue($this->policy->update($this->user, $this->sport));
    }

    public function test_delete(): void
    {
        $this->assertTrue($this->policy->delete($this->user, $this->sport));
    }

    public function test_restore(): void
    {
        $this->assertTrue($this->policy->restore($this->user, $this->sport));
    }

    public function test_force_delete(): void
    {
        $this->assertTrue($this->policy->forceDelete($this->user, $this->sport));
    }
}
