<?php

namespace Tests\Unit\Policies;

use App\Models\Team;
use App\Models\User;
use App\Policies\TeamPolicy;
use Tests\TestCase;

class TeamPolicyTest extends TestCase
{
    private Team $team;

    private TeamPolicy $policy;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->team = new Team;
        $this->user = new User;
        $this->policy = new TeamPolicy;
    }

    public function test_view_any(): void
    {
        $this->assertTrue($this->policy->viewAny($this->user));
    }

    public function test_view(): void
    {
        $this->assertTrue($this->policy->view($this->user, $this->team));
    }

    public function test_create(): void
    {
        $this->assertTrue($this->policy->create($this->user));
    }

    public function test_update(): void
    {
        $this->assertTrue($this->policy->update($this->user, $this->team));
    }

    public function test_delete(): void
    {
        $this->assertTrue($this->policy->delete($this->user, $this->team));
    }

    public function test_restore(): void
    {
        $this->assertTrue($this->policy->restore($this->user, $this->team));
    }

    public function test_force_delete(): void
    {
        $this->assertTrue($this->policy->forceDelete($this->user, $this->team));
    }
}
