<?php

namespace Tests\Unit\Request;

use App\Http\Requests\UpdatePersonRequest;
use Tests\TestCase;

class UpdatePersonRequestTest extends TestCase
{
    private UpdatePersonRequest $request;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = new UpdatePersonRequest;
    }

    /**
     * A basic unit test example.
     */
    public function test_authorize(): void
    {
        $this->assertTrue($this->request->authorize());
    }

    public function test_rules(): void
    {
        $this->assertEquals(

            ['name' => 'string|required|max:255',
                'bio' => 'string|nullable',
                'dob' => 'date|nullable',
                'user_id' => 'integer|exists:users,id|nullable',
            ],
            $this->request->rules()
        );
    }
}
