<?php

namespace Tests\Feature\Application;

use App\Models\User;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class DevServicesControllerTest extends TestCase
{
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User;
    }

    public function test_invoke(): void
    {
        $response = $this->actingAs($this->user)->get(route('dev-services'));

        $response->assertStatus(200);
        $response->assertInertia(fn(AssertableInertia $page) => $page->component('DevServices') );
    }
}
