<?php

namespace Tests\Feature\Application;

use App\Models\Person;
use App\Models\User;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class IndexControllerTest extends TestCase
{
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User;
    }

    /**
     * A basic feature test example.
     */
    public function test_invoke(): void
    {
        $numPeople = 10;
        Person::factory($numPeople)->create();
        $response = $this->actingAs($this->user)->get(route('index'));
        $response->assertStatus(200);
        $response->assertInertia(fn (AssertableInertia $page) => $page->where('peopleCount', $numPeople));
    }
}
