<?php

namespace Tests\Feature\Application;

use App\Models\Person;
use App\Models\User;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class PersonControllerTest extends TestCase
{
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User;
    }

    /**
     * A basic feature test example.
     */
    public function test_example(): void
    {
        $people = Person::factory(10)->create();
        $response = $this->actingAs($this->user)->get(route('person.index'));

        $response->assertStatus(200);
        $response->assertInertia(function (AssertableInertia $page) use ($people) {
            $page->component('Person/Index')
                ->has('people', $people->count(), function (AssertableInertia $page) use ($people) {
                    $firstPerson = $people->first();
                    $page
                        ->where('name', $firstPerson->name)
                        ->where('bio', $firstPerson->bio)
                        ->where('dob', $firstPerson->dob->jsonSerialize())
                        ->etc();
                });
        });
    }
}
