<?php

namespace Tests\Feature\Application;

use App\Models\Sport;
use App\Models\User;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class SportControllerTest extends TestCase
{
    protected User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User;
    }

    public function test_index(): void
    {
        $sports = Sport::factory(10)->create();
        $response = $this->actingAs($this->user)->get(route('sport.index'));

        $response->assertStatus(200);
        $response->assertInertia(fn (AssertableInertia $page) => $page->component('Sport/Index')
            ->has(
                'sports',
                $sports->count(),
                fn (AssertableInertia $page) => $page
                    ->where('name', $sports->first()->name)
                    ->where('description', $sports->first()->description)
                    ->where('colour', $sports->first()->colour)
                    ->etc(),
            ));
    }

    public function test_create(): void
    {
        $users = User::factory(10)->create();
        $response = $this->actingAs($this->user)->get(route('sport.create'));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Sport/Create')
        );
    }

    public function test_store(): void
    {
        $response = $this->actingAs($this->user)->post(route('sport.store'), [
            'name' => 'Test Sport 1',
            'description' => 'Test Sport 1 Bio',
            'colour' => '#BAD455',
        ]);
        $response->assertRedirectToRoute('sport.index');
    }

    public function test_show(): void
    {
        $sport = Sport::factory()->create();
        $response = $this->actingAs($this->user)->get(route('sport.show', ['sport' => $sport]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Sport/Show')
                ->has(
                    'sport',
                    fn (AssertableInertia $page) => $page
                        ->where('id', $sport->id)
                        ->etc(),
                ),
        );
    }

    public function test_edit(): void
    {
        $sport = Sport::factory()->create();
        $response = $this->actingAs($this->user)->get(route('sport.edit', ['sport' => $sport]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Sport/Edit')
                ->has(
                    'sport',
                    fn (AssertableInertia $page) => $page
                        ->where('id', $sport->id)
                        ->etc(),
                )
        );
    }

    public function test_update(): void
    {
        $newName = self::class;
        $newColour = '#BAD455';
        $sport = Sport::factory()->create();
        $response = $this
            ->actingAs($this->user)
            ->put(
                route(
                    'sport.update',
                    ['sport' => $sport],
                ),
                [
                    'name' => $newName,
                    'description' => null,
                    'colour' => $newColour,
                ],
            );
        $response->assertRedirectToRoute('sport.index');
        $sport->refresh();
        $this->assertEquals($newName, $sport->name);
        $this->assertEquals($newColour, $sport->colour);
    }

    public function test_destroy(): void
    {
        $sport = Sport::factory()->create();
        $this->assertNull($sport->deleted_at);

        $response = $this->actingAs($this->user)->delete(route('sport.destroy', ['sport' => $sport]));
        $response->assertRedirectToRoute('sport.index');
        $sport->refresh();
        $this->assertNotNull($sport->deleted_at);
    }
}
