<?php

namespace Tests\Feature\Application;

use App\Models\Position;
use App\Models\Sport;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class SportPositionControllerTest extends TestCase
{
    protected Sport $sport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sport = Sport::factory()->has(Position::factory(5))->create();
    }

    public function test_index(): void
    {
        $response = $this->actingAs($this->user)->get(route('sport.position.index', ['sport' => $this->sport]));

        $response->assertStatus(200);
        $response->assertInertia(fn (AssertableInertia $page) => $page->component('Position/Index')
            ->has(
                'sport.positions',
                $this->sport->positions->count(),
            ));
    }

    public function test_create(): void
    {
        $response = $this
            ->actingAs($this->user)
            ->get(route('sport.position.create', ['sport' => $this->sport]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Position/Create')
                ->where('sport.id', $this->sport->id)
        );
    }

    public function test_store(): void
    {
        $testStoreName = 'test_store'.self::class;
        $previewPosition = 50;
        $response = $this->actingAs($this->user)->post(route('sport.position.store', ['sport' => $this->sport]), [
            'name' => $testStoreName,
            'preview_position_x' => $previewPosition,
            'preview_position_y' => $previewPosition,
        ]);
        $this->sport->refresh();
        $response->assertRedirectToRoute('sport.position.index', ['sport' => $this->sport]);
        $this->assertContains($testStoreName, $this->sport->positions->pluck('name'));
    }

    //    public function test_show(): void
    //    {
    //        $sport = Sport::factory()->create();
    //        $response = $this->actingAs($this->user)->get(route('sport.show', ['sport' => $sport]));
    //
    //        $response->assertStatus(200);
    //        $response->assertInertia(
    //            fn (AssertableInertia $page) => $page
    //                ->component('Sport/Show')
    //                ->has(
    //                    'sport',
    //                    fn (AssertableInertia $page) => $page
    //                        ->where('id', $sport->id)
    //                        ->etc(),
    //                ),
    //        );
    //    }

    public function test_edit(): void
    {
        $position = $this->sport->positions->first();
        $response = $this
            ->actingAs($this->user)
            ->get(route('sport.position.edit', ['sport' => $this->sport, 'position' => $position]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Position/Edit')
                ->has(
                    'sport',
                    fn (AssertableInertia $page) => $page
                        ->where('id', $this->sport->id)
                        ->etc(),
                )
        );
    }

    public function test_update(): void
    {
        $newName = 'test_update'.self::class;
        $position = $this->sport->positions->first();
        $response = $this
            ->actingAs($this->user)
            ->put(
                route(
                    'sport.position.update',
                    [
                        'sport' => $this->sport,
                        'position' => $position,
                    ],
                ),
                [
                    'name' => $newName,
                    'description' => null,
                ],
            );
        $response->assertRedirectToRoute('sport.position.index', ['sport' => $this->sport]);
        $position->refresh();
        $this->assertEquals($newName, $position->name);
    }

    public function test_destroy(): void
    {
        $position = $this->sport->positions->last();
        $this->assertNull($position->deleted_at);

        $response = $this->actingAs($this->user)->delete(route('sport.position.destroy', ['sport' => $this->sport, 'position' => $position]));
        $response->assertRedirectToRoute('sport.position.index', ['sport' => $this->sport]);
        $position->refresh();
        $this->assertNotNull($position->deleted_at);
    }
}
