<?php

namespace Tests\Feature\Application;

use App\Models\Sport;
use App\Models\Team;
use App\Models\User;
use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

class TeamControllerTest extends TestCase
{
    protected User $user;
    protected Sport $sport;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User;
        $this->sport = Sport::factory()->create();
    }

    public function test_index(): void
    {
        $teams = Team::factory(10)->create();
        $response = $this->actingAs($this->user)->get(route('team.index'));

        $response->assertStatus(200);
        $response->assertInertia(fn (AssertableInertia $page) => $page->component('Team/Index')
            ->has(
                'teams',
                $teams->count(),
                fn (AssertableInertia $page) => $page
                    ->where('name', $teams->first()->name)
                    ->where('description', $teams->first()->description)
                    ->where('address', $teams->first()->address)
                    ->etc(),
            ));
    }

    public function test_create(): void
    {
        $users = User::factory(10)->create();
        $response = $this->actingAs($this->user)->get(route('team.create'));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Team/Create')
        );
    }

    public function test_store(): void
    {
        $response = $this->actingAs($this->user)->post(route('team.store'), [
            'name' => 'Test Team 1',
            'description' => 'Test Team 1 Bio',
            'address' => '1997-04-15',
            'sport_id' => (string) $this->sport->id,
        ]);
        $response->assertRedirectToRoute('team.index');
    }

    public function test_show(): void
    {
        $team = Team::factory()->create();
        $response = $this->actingAs($this->user)->get(route('team.show', ['team' => $team]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Team/Show')
                ->has(
                    'team',
                    fn (AssertableInertia $page) => $page
                        ->where('id', $team->id)
                        ->etc(),
                ),
        );
    }

    public function test_edit(): void
    {
        $team = Team::factory()->create();
        $response = $this->actingAs($this->user)->get(route('team.edit', ['team' => $team]));

        $response->assertStatus(200);
        $response->assertInertia(
            fn (AssertableInertia $page) => $page
                ->component('Team/Edit')
                ->has(
                    'team',
                    fn (AssertableInertia $page) => $page
                        ->where('id', $team->id)
                        ->etc(),
                )
        );
    }

    public function test_update(): void
    {
        $newName = self::class;
        $team = Team::factory()->create();
        $response = $this
            ->actingAs($this->user)
            ->put(
                route(
                    'team.update',
                    ['team' => $team],
                ),
                [
                    'name' => $newName,
                    'description' => null,
                    'address' => null,
                    'sport_id' => $this->sport->id,
                ],
            );
        $response->assertRedirectToRoute('team.index');
        $team->refresh();
        $this->assertEquals($newName, $team->name);
    }

    public function test_destroy(): void
    {
        $team = Team::factory()->create();
        $this->assertNull($team->deleted_at);

        $response = $this->actingAs($this->user)->delete(route('team.destroy', ['team' => $team]));
        $response->assertRedirectToRoute('team.index');
        $team->refresh();
        $this->assertNotNull($team->deleted_at);
    }
}
